Add flag to only search IRIS (avoiding Winston!)
uafgeotools/waveform_collection pull request #25
Opened 2022-03-03 04:12 UTC by liamtoney

This addresses https://github.com/uafgeotools/waveform_collection/issues/18#issuecomment-1057636587.

2022-03-08 20:32 UTC, liamtoney commented
Note that the diff looks large; this is only because of indenting changes!

2022-04-06 20:04 UTC, liamtoney commented
There was some discussion of having the flag set to `True` by default — as we usually only seek IRIS data.

2022-04-06 20:14 UTC, davidfee5 commented on waveform_collection/server.py
> +                          watc_username=None, watc_password=None, iris_only=False):
As discussed, I think we should set default to iris_only=True since that is the standard FDSN server we use

2022-04-06 20:18 UTC, davidfee5 requested changes
Looks good other than the iris_only default change!

2022-04-06 22:21 UTC, liamtoney commented
Because of this change, any code w/o this flag will only be grabbing IRIS data. This mightttt break something, but I don't think it is crucial enough. So we can merge.

2022-04-06 22:21 UTC, merged